version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
    open-pull-requests-limit: 15
    reviewers:
      - "farhan-ahmed1"
    assignees:
      - "farhan-ahmed1"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    versioning-strategy: "increase"
    groups:
      typescript:
        patterns:
          - "typescript"
          - "@types/*"
      eslint:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
      testing:
        patterns:
          - "vitest*"
          - "@vitest/*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
    open-pull-requests-limit: 8
    reviewers:
      - "farhan-ahmed1"
    assignees:
      - "farhan-ahmed1"
    commit-message:
      prefix: "ci"
      include: "scope"
