name: HanCover Action
description: |
  Generate comprehensive coverage reports for Pull Requests with intelligent change detection and dynamic badges.
  
  Features:
  • Multi-format support: Automatically detects LCOV, Cobertura, JaCoCo, and Clover coverage files
  • Smart PR comments: Single sticky comment that updates with each push - no spam
  • Change tracking: Compares PR coverage against main branch with visual delta indicators  
  • Dynamic badges: Auto-updating coverage and change badges via GitHub Gists or file storage
  • Package organization: Intelligent grouping with customizable package structure
  • Security focused: Minimal permissions, input validation, and secure parsing
  • Security focused: Minimal permissions, input validation, and secure XML processing
  • Threshold validation: Configurable coverage requirements with clear pass/fail indicators
  
  Perfect for JavaScript/TypeScript (Jest, Vitest), .NET, Java (Maven), Python, PHP, and monorepo projects.
author: FarHan Labs
branding:
  icon: 'shield'
  color: 'green'

runs:
  using: node20
  main: dist/index.js

inputs:
  files:
    description: "Coverage file patterns (e.g., 'coverage/lcov.info', '**/cobertura.xml')"
    required: true
  github-token:
    description: "GitHub token for PR comments and GitHub API access (defaults to GITHUB_TOKEN)"
    required: false
  gist-token:
    description: "GitHub token with 'gist' scope for baseline storage"
    required: false
  gist-id:
    description: "GitHub Gist ID for storing baseline coverage data (enables change badges)"
    required: false
  min-threshold:
    description: "Minimum coverage threshold for health indicators (default: 50)"
    required: false
    default: "50"
  comment-mode:
    description: "'update' (sticky comment) or 'new' (always create new)"
    required: false
    default: "update"
  warn-only:
    description: "If true, don't fail the action on coverage threshold violations"
    required: false
    default: "false"
  baseline-files:
    description: "Baseline coverage files for comparison (alternative to gist-id)"
    required: false
  groups:
    description: "YAML configuration for custom package grouping"
    required: false
  thresholds:
    description: "Coverage thresholds (e.g., 'total:80\\ndiff:75')"
    required: false

outputs:
  coverage-pct:
    description: "Overall project coverage percentage"
  changes-coverage-pct:
    description: "Coverage percentage for code changes in this PR"
  coverage-delta:
    description: "Coverage change compared to main branch (when gist-id provided)"
