name: HanCover — Coverage Reports for PRs
description: |
  Generate comprehensive coverage reports with change detection for Pull Requests.
  Supports LCOV, Cobertura, JaCoCo, and Clover formats. Posts sticky PR comments 
  with coverage badges and change indicators. Uses GitHub Gists for baseline storage.
author: FarHan Labs
branding:
  icon: 'shield'
  color: 'green'

runs:
  using: node20
  main: dist/index.js

inputs:
  files:
    description: "Coverage file patterns (e.g., 'coverage/lcov.info', '**/cobertura.xml')"
    required: true
  github-token:
    description: "GitHub token for API access (defaults to GITHUB_TOKEN)"
    required: false
  gist-id:
    description: "GitHub Gist ID for storing baseline coverage data (enables change badges)"
    required: false
  min-threshold:
    description: "Minimum coverage threshold for health indicators (default: 50)"
    required: false
    default: "50"
  comment-mode:
    description: "'update' (sticky comment) or 'new' (always create new)"
    required: false
    default: "update"
  warn-only:
    description: "If true, don't fail the action on coverage threshold violations"
    required: false
    default: "false"
  baseline-files:
    description: "Baseline coverage files for comparison (alternative to gist-id)"
    required: false
  groups:
    description: "YAML configuration for custom package grouping"
    required: false
  thresholds:
    description: "Coverage thresholds (e.g., 'total:80\\ndiff:75')"
    required: false

outputs:
  coverage-pct:
    description: "Overall project coverage percentage"
  changes-coverage-pct:
    description: "Coverage percentage for code changes in this PR"
  coverage-delta:
    description: "Coverage change compared to main branch (when gist-id provided)"
