# Basic PR Coverage Example
# This workflow adds coverage reports to PRs without change detection or badges.
# Copy this file to .github/workflows/pr-coverage.yml in your repository.

name: PR Coverage Report
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Coverage Report
        uses: farhan-ahmed1/hancover-action@v1
        with:
          files: coverage/lcov.info
          min-threshold: 80
          comment-mode: update

# What this provides:
# - Clean PR comments with coverage tables
# - Package-based organization
# - Coverage percentage and health indicators
# - Updates existing comments instead of creating new ones
# 
# What this doesn't include:
# - Coverage badges
# - Change detection vs main branch
# - Dynamic README badges
