# Example Coverage Badge Workflow
# Copy this file to your repository as .github/workflows/coverage-badge.yml

name: Coverage Badge

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  coverage-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Generate coverage badge data
        id: coverage
        run: |
          # Extract coverage percentage from test output
          COVERAGE_OUTPUT=$(npm test -- --coverage 2>&1)
          COVERAGE=$(echo "$COVERAGE_OUTPUT" | grep "All files" | awk '{print $4}' | head -1 | cut -d. -f1)
          
          if [ -z "$COVERAGE" ]; then
            echo "Could not extract coverage percentage"
            exit 1
          fi
          
          # Determine color based on coverage
          if [ $COVERAGE -ge 90 ]; then
            COLOR="brightgreen"
          elif [ $COVERAGE -ge 80 ]; then
            COLOR="green"  
          elif [ $COVERAGE -ge 70 ]; then
            COLOR="yellow"
          elif [ $COVERAGE -ge 60 ]; then
            COLOR="orange"
          else
            COLOR="red"
          fi
          
          echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT
          echo "color=$COLOR" >> $GITHUB_OUTPUT
          echo "Coverage: $COVERAGE% (Color: $COLOR)"

      - name: Create coverage badge JSON
        run: |
          cat > coverage-badge.json << EOF
          {
            "schemaVersion": 1,
            "label": "coverage",
            "message": "${{ steps.coverage.outputs.coverage }}%",
            "color": "${{ steps.coverage.outputs.color }}"
          }
          EOF

      - name: Upload coverage badge data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: coverage-badge.json
          retention-days: 30
