# Enhanced Coverage with Badges and Change Detection
# This workflow provides full coverage reporting with dynamic badges and change tracking.
# Copy these files to your .github/workflows/ directory.

# =============================================================================
# File 1: .github/workflows/coverage-pr.yml
# =============================================================================
name: PR Coverage with Change Detection
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Coverage Report with Change Detection
        uses: farhan-ahmed1/hancover-action@v1
        with:
          files: coverage/lcov.info
          gist-id: ${{ secrets.COVERAGE_GIST_ID }}
          github-token: ${{ secrets.GIST_TOKEN }}
          min-threshold: 80
          comment-mode: update

# =============================================================================
# File 2: .github/workflows/coverage-main.yml  
# =============================================================================
# name: Update Coverage Baseline
# on:
#   push:
#     branches: [main]
#
# permissions:
#   contents: read
#
# jobs:
#   update-baseline:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#
#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '20'
#           cache: 'npm'
#
#       - name: Install dependencies
#         run: npm ci
#
#       - name: Run tests with coverage
#         run: npm test -- --coverage
#
#       - name: Update Coverage Baseline
#         uses: farhan-ahmed1/hancover-action@v1
#         with:
#           files: coverage/lcov.info
#           gist-id: ${{ secrets.COVERAGE_GIST_ID }}
#           github-token: ${{ secrets.GIST_TOKEN }}

# =============================================================================
# Setup Instructions:
# =============================================================================
# 1. Create a GitHub Gist:
#    - Go to https://gist.github.com
#    - Create a public gist with filename: coverage.json
#    - Content: {"coverage": 0}
#    - Note the gist ID from the URL (e.g., abc123def456789)
#
# 2. Create a Personal Access Token:
#    - Go to GitHub Settings → Developer settings → Personal access tokens
#    - Create a token with 'gist' scope
#
# 3. Add Repository Secrets:
#    - Repository Settings → Secrets and variables → Actions
#    - Add COVERAGE_GIST_ID: your gist ID
#    - Add GIST_TOKEN: your personal access token
#
# 4. Add README Badge:
#    Replace USERNAME and GIST_ID in this markdown:
#    ![Coverage](https://img.shields.io/endpoint?url=https://gist.githubusercontent.com/USERNAME/GIST_ID/raw/coverage-badge.json)
#
# This provides:
# - Coverage badges in PR comments
# - Change detection (shows +/- vs main branch)
# - Dynamic README badge that auto-updates
# - Sticky PR comments that update on each push
