# Multi-Format Coverage Support
# This example shows how to use the action with different coverage formats.
# The action automatically detects the format, so no special configuration is needed.

name: Multi-Format Coverage
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  # JavaScript/TypeScript with Jest or Vitest (LCOV format)
  frontend-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - run: npm ci
      - run: npm test -- --coverage
      
      - name: Frontend Coverage Report
        uses: farhan-ahmed1/hancover-action@v1
        with:
          files: coverage/lcov.info
          min-threshold: 80

  # .NET Projects (Cobertura format)
  dotnet-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
      
      - run: dotnet restore
      - run: dotnet test --collect:"XPlat Code Coverage" --results-directory coverage
      
      - name: .NET Coverage Report
        uses: farhan-ahmed1/hancover-action@v1
        with:
          files: coverage/**/coverage.cobertura.xml
          min-threshold: 75

  # Java Projects (JaCoCo format)
  java-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - run: ./mvnw test jacoco:report
      
      - name: Java Coverage Report
        uses: farhan-ahmed1/hancover-action@v1
        with:
          files: target/site/jacoco/jacoco.xml
          min-threshold: 70

  # Python Projects (Cobertura format)
  python-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - run: |
          pip install coverage pytest
          coverage run -m pytest
          coverage xml
      
      - name: Python Coverage Report
        uses: farhan-ahmed1/hancover-action@v1
        with:
          files: coverage.xml
          min-threshold: 85

  # PHP Projects (Clover format)
  php-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug
      
      - run: composer install
      - run: vendor/bin/phpunit --coverage-clover coverage.xml
      
      - name: PHP Coverage Report
        uses: farhan-ahmed1/hancover-action@v1
        with:
          files: coverage.xml
          min-threshold: 80

  # Multiple files with glob patterns
  combined-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # ... run your tests that generate multiple coverage files ...
      
      - name: Combined Coverage Report
        uses: farhan-ahmed1/hancover-action@v1
        with:
          files: |
            packages/*/coverage/lcov.info
            apps/*/coverage/cobertura.xml
            services/*/target/site/jacoco/jacoco.xml
          min-threshold: 75

# Notes:
# - The action automatically detects file formats based on content
# - Supported formats: LCOV (.info), Cobertura (.xml), JaCoCo (.xml), Clover (.xml)
# - You can mix and match different formats in the same action call
# - Use glob patterns to collect multiple coverage files
# - Each format preserves its native metrics (lines, branches, functions/methods)
