# Example workflow demonstrating the enhanced coverage reporting
# This shows how to generate both PR coverage and baseline coverage for comparison

name: Enhanced Coverage Report

on:
  pull_request:
    branches: [main]

jobs:
  coverage-with-baseline:
    runs-on: ubuntu-latest
    steps:
      # Checkout with full history for baseline comparison
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # --- PR HEAD COVERAGE ---
      - name: Install dependencies (PR head)
        run: npm ci

      - name: Run tests with coverage (PR head)
        run: npm test -- --coverage

      - name: Save PR coverage
        run: |
          mkdir -p coverage-reports
          cp coverage/lcov.info coverage-reports/pr.lcov
          # If using Cobertura: cp coverage/cobertura-coverage.xml coverage-reports/pr.xml

      # --- MAIN BASELINE COVERAGE ---
      - name: Checkout main (baseline)
        run: |
          # Stash any uncommitted changes (like coverage-reports files)
          git stash push -u -m "Stash coverage reports before baseline checkout"
          git checkout origin/main
          npm ci

      - name: Run tests with coverage (main)
        run: npm test -- --coverage

      - name: Save main coverage
        run: |
          cp coverage/lcov.info coverage-reports/main.lcov
          # If using Cobertura: cp coverage/cobertura-coverage.xml coverage-reports/main.xml

      - name: Checkout back to PR
        run: |
          git checkout ${{ github.event.pull_request.head.sha }}
          # Restore the stashed coverage reports
          git stash pop || echo "No stash to restore"

      # --- GENERATE ENHANCED COVERAGE REPORT ---
      - name: Coverage Report with Baseline
        uses: ./
        with:
          files: coverage-reports/pr.lcov
          baseline-files: coverage-reports/main.lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-ref: ${{ github.event.pull_request.base.sha }}
          thresholds: |
            total:80
            diff:75
            branches:70
          min-threshold: 60
          comment-mode: update

  # Alternative simpler version without baseline
  coverage-simple:
    runs-on: ubuntu-latest
    if: false  # Disable this job, just showing as example
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install and test
        run: |
          npm ci
          npm test -- --coverage

      - name: Coverage Report (Simple)
        uses: ./
        with:
          files: coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
          thresholds: |
            total:80
            diff:75
          min-threshold: 50
