# Workflow to update coverage data file on main branch via PR
# This creates a PR to update the baseline coverage data

name: Update Coverage Data via PR

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-coverage-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Update Coverage Data File
        uses: ./
        with:
          files: coverage/lcov.info
          coverage-data-path: .github/coverage-data.json

      - name: Create Pull Request for coverage data update
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update coverage data [skip ci]'
          title: 'Update coverage data'
          body: |
            This PR updates the coverage data file based on the latest test results.
            
            This is an automated PR created by the coverage update workflow.
          branch: update-coverage-data
          delete-branch: true
          author: GitHub Action <action@github.com>
          committer: GitHub Action <action@github.com>
